#!/bin/bash

echo "Active Internet connections (only servers)"
ss -tulnpx | awk '
BEGIN { print "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name" }
NR>1 { print }'
